DROP TABLE Coordina; 
DROP TABLE Asiste;
DROP TABLE Imparte; 
DROP TABLE Abona;
DROP TABLE Actividad;
DROP TABLE Empleado_AML;
DROP TABLE Socio_Suscripcion;

CREATE TABLE Socio_Suscripcion (
  DNI_Socio VARCHAR(20) NOT NULL,
  Nombre VARCHAR(255) NULL,
  Tlf INTEGER NULL,
  IBAN INTEGER NULL,
  Tipo VARCHAR(255) NULL,
  PRIMARY KEY(DNI_Socio)
);

CREATE TABLE Empleado_AML (
  DNI_E VARCHAR(45)  NOT NULL,
  Nombre VARCHAR(255) NULL,
  Sueldo INTEGER NULL,
  Rol VARCHAR(45) NULL,
  Horario VARCHAR(45) NULL,
  Turno VARCHAR(45) NULL,
  Dpto VARCHAR(45) NULL,
  PRIMARY KEY(DNI_E)
);

CREATE TABLE Actividad (
  ID INTEGER  NOT NULL,
  Nombre VARCHAR(45)  NULL,
  Días VARCHAR(45) NULL,
  Horas VARCHAR(45) NULL,
  Aforo INTEGER NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Abona (
  Fecha VARCHAR(255) NOT NULL,
  DNI_Socio VARCHAR(20) NOT NULL,
  PRIMARY KEY(Fecha, DNI_Socio),
  FOREIGN KEY(DNI_Socio)
    REFERENCES Socio_Suscripcion(DNI_Socio)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Imparte (
  Actividad_ID INTEGER  NOT NULL,
  DNI_E VARCHAR(45)  NOT NULL,
  PRIMARY KEY(Actividad_ID, DNI_E),
  FOREIGN KEY(DNI_E)
    REFERENCES Empleado_AML(DNI_E)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Actividad_ID)
    REFERENCES Actividad(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Asiste (
  Fecha VARCHAR(45)  NOT NULL,
  Actividad_ID INTEGER NOT NULL,
  DNI_Socio VARCHAR(20) NOT NULL,
  PRIMARY KEY(Fecha, Actividad_ID, DNI_Socio),
  FOREIGN KEY(DNI_Socio)
    REFERENCES Socio_Suscripcion(DNI_Socio)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Actividad_ID)
    REFERENCES Actividad(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Coordina (
  Mes VARCHAR NOT NULL,
  Actividad_ID INTEGER  NOT NULL,
  DNI_E VARCHAR(45)  NOT NULL,
  PRIMARY KEY(Mes, Actividad_ID),
  FOREIGN KEY(DNI_E)
    REFERENCES Empleado_AML(DNI_E)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Actividad_ID)
    REFERENCES Actividad(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


